name: ec3318
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - matplotlib
  - scipy
  - pip:
    - plotnine>=0.10
    - mizani>=0.8
    - yfinance>=0.2.18
    - PyPortfolioOpt>=1.5.2
    - adjustText>=0.8
    - requests>=2.26
